### ISSUE TITLE
[FR] Remove Glow, Change All Fonts, Size in Custom Auras

### ISSUE THREAD

**Issue by webdevdave** [Voopie/Stripes#1]
Really liking your nameplates addon so far! Here are my suggestions so far...

I'd prefer to be able to keep all my bars with a flat texture, but it seems that even though I have changed them all, when selecting a target there is still a texture in the bars...
![Screenshot 2021-08-23 142157](https://user-images.githubusercontent.com/56913415/130497716-b80c58fd-55ca-4631-a329-7e1787a78743.png)
I've noticed this texture in the cast bar too.

Also, I wanted to change my font and had to search around to find all the font selectors. It would be nice to add the ability to change all fonts at once.

Finally, in the Auras > Custom section. other than a border color to emphasize the spell (I don't think the border is working, I added Fiery Brand as a debuff and don't see a difference) it would be nice if I could make the selected buff larger too.

Thanks, hope this helps!!!

**Comment by Voopie** [comment]
Hmm... Now I checked, the texture seems to be changing... Do you have "Stripes Flat"?
Maybe you should try a different texture? Like "Stripes Liline", but it's a bit brighter.
But anyway, I'll try to add more textures for every taste :)

About font selectors: yes... there are too many of them, I will make a global font selection in the next release

Custom auras appear at the top right of the health bar, as in the image:
![custom_demo](https://user-images.githubusercontent.com/1324849/130517631-3795020e-a586-4b61-a62e-775651413805.jpg)

Most likely this spell was added with ID 204021, while the required debuff has ID **207771**

And check 'own' and 'debuff' (these are the little buttons on the left)
![image](https://user-images.githubusercontent.com/1324849/130518927-24b956dc-1d8f-4f22-ad61-f62bc79229a3.png)


No, it's thank you! ☺

**Comment by webdevdave** [comment]
Hey, thanks for getting back to me... I love when an addon dev is responsive!

I am using a texture called "SkullflowerNeon" that is from my own textures. It has a really nice gradient that goes across the bar, rather than top to bottom. Here is how it looks on Plater...
![Screenshot 2021-08-23 211816](https://user-images.githubusercontent.com/56913415/130540212-3c84e193-a9da-4403-9baf-22766de0a73c.png)

If interested, I'm including the files needed for that texture for you to use. I will also include the target arrows (which I am rather fond of), and the fonts I use. Feel free to use any/all of them!

[nameplate-files.zip](https://github.com/Voopie/Stripes/files/7035762/nameplate-files.zip)

I see you put out an update, I'll go check it out now. Thanks again!

**Comment by webdevdave** [comment]
Two more small things...

You were right, I had the wrong Fiery Brand ID... but after fixing it, I am now seeing the debuff twice. I would suggest you make it so if something is in the custom buff section, you don't see it in the main buff area too.
![InkedScreenshot 2021-08-23 213726_LI](https://user-images.githubusercontent.com/56913415/130541879-f8647b39-a286-4f18-89b6-095bd05a2c85.jpg)

Also, I noticed a small spelling error. It should read "Dispellable" with 2 L's :)
![Screenshot 2021-08-23 213803](https://user-images.githubusercontent.com/56913415/130541942-c6666ca0-3b6d-4811-8011-a82f72d38e5a.png)

Thanks again! :)

**Comment by Voopie** [comment]
I found the glow you were talking about and will make it optional

About custom aura and duplication: As a temporary solution, you can add Fiery Brand to the blacklist :)
And I will also make it possible to automatically disable duplication

**Comment by Voopie** [comment]
Question: How did you do this health formatting? 😲
Because it's not on my list
![image](https://user-images.githubusercontent.com/1324849/130605086-d7f3b78a-0897-490c-acb5-4dcbc0e9f6e5.png)

**Comment by webdevdave** [comment]
Hehe... if you read it again you'll notice I wrote "Here is how it looks on **Plater**..." That one screenshot was showing you how the gradient looked when I used Plater. So that is why it looks different. It is also showing different target arrows from what you have.

The last image (with the red circle I drew) is with Stripes. :)

**Comment by Voopie** [comment]
I was just talking about the second screenshot
Your health format looks like this - 1.29m **/** (99.9%)
But with brackets in my addon only 1.29m (99.9%) without the slash

And by the way, almost everything is ready from what you asked ;)

**Comment by webdevdave** [comment]
So I checked into the health formatting... I have this one selected...
![Screenshot 2021-08-24 134117](https://user-images.githubusercontent.com/56913415/130664066-b66b71ff-449e-4595-9fb0-eb6b8f5114a2.png)
And when I hit the target dummy and it is less than 100% it adds the slash :)

I also added Fiery Brand to the Blacklist, like you suggested (using the same ID as in my Custom Aura of 207771)...
![Screenshot 2021-08-24 133847](https://user-images.githubusercontent.com/56913415/130664208-db8d1a72-dd5e-4359-9b47-faebc2beb794.png)

but it didn't seem to work. They are also running into each other...
![Screenshot 2021-08-24 133741](https://user-images.githubusercontent.com/56913415/130664411-876d75d1-8484-476a-b889-bb60776779a8.png)

Looking forward to your updates!! :)

**Comment by Voopie** [comment]
Try **204021** in blacklist 😄

**Comment by webdevdave** [comment]
204021 did the trick!

If you don't mind my bothering you with more suggestions, I see that you are allowing the changing of colors for the threat situations (which is great because I play a Tank), but it would be awesome if I could adjust the regular colors a bit too. I like to make my colors a bit more pastel, like the ones I'm using for threat here...
![threat](https://user-images.githubusercontent.com/56913415/130698046-10e2e6f4-d0f2-4699-bd14-8bad27121670.png)

Thanks again!

**Comment by Voopie** [comment]
Also almost done! 
![image](https://user-images.githubusercontent.com/1324849/130822446-cffacb55-ffb7-430f-8969-02819282a885.png)

```
Enemy NPC      Enemy players
Friendly NPC   Friendly players
Neutral
Tapped   Disconnected
```

**Comment by webdevdave** [comment]
You da man! When do you think it'll be posted? I'm excited to try it out!

**Comment by Voopie** [comment]
I think I'll release it tomorrow

**Comment by webdevdave** [comment]
Happy to help you test stuff if you'd like too

**Comment by Voopie** [comment]
If you're still awake, catch this :)
**[Stripes-1.9.zip](https://github.com/Voopie/Stripes/files/7050377/Stripes-1.9.zip)**
Because I have already gone to bed and if there are no bugs by tomorrow, I will release this 

Current changelog:
- New options: HP bar custom colors by unit type & reaction
- New option: Turn on (or off) the highlight when selecting a target
- New options: Custom auras scale & y-offset options
- New: Global category & global font options
- Updated: Auto/manual adding to blacklist in custom auras
- Updated NPCs list for Custom HP bar colors (Xira the Underhanded returned to the Theater of Pain)
- Updated spell list in Spell Interrupted
- Fixed some health text formats
- Fixed 'own mode' for custom auras
- Fixed missing auras when using sorting
- Fixed HP bar coloring when removing raid target icon
- Added Google Sans font
- Added new status bar texture (Skullflower Neon)
- Updated enUS localization
- Code improvements & optimizations

**Comment by webdevdave** [comment]
Only 7pm where I am... I'll check it out now though. Thanks! :)

**Comment by Voopie** [comment]
Hey! Version 1.9 was released!
I advise you to update because the version I sent you yesterday is missing some of the improvements and fixes I made today

**Comment by webdevdave** [comment]
Thanks, I will! I'll play a bit with it tonight and get back to you with any other ideas I might have! :D

**Comment by webdevdave** [comment]
Really liking it so far. One suggestion for ya (so far lol) that I think would really make your addon stand out... 
I have a Plater Mod that turns the spell cast bar on the nameplate Dark Blue if it is interruptable but your interrupt is on cooldown OR light blue if your interrupt is on cd but it will be ready before the cast ends (so you can still spam interrupt and get it in time). After not having this feature, I realized just how useful it was and how much I missed it! This is the mod I'm talking about, maybe you can review its code and implement it...
https://wago.io/jHilJiXiY

Thanks again! Looking forward to your reply/updates!

**Comment by Voopie** [comment]
You won't believe this! I was just today thinking about such a feature, only a little extended 😁

**Comment by webdevdave** [comment]
Do you think you'll be adding the interrupt color feature soon? It's so useful! :)

**Comment by Voopie** [comment]
Not soon, but already ;)
Just needs a little polishing and it's done

**Comment by webdevdave** [comment]
Great! Can't wait to try it out!

**Comment by Voopie** [comment]
Version 1.10 released

**Comment by webdevdave** [comment]
Nice! Gonna go check it out now!

**Comment by Voopie** [comment]
You can join our discord. I think it would be easier to discuss new stuff there :)
https://discord.gg/rWy6KG94ec

**Comment by webdevdave** [comment]
Awesome! Just joined! I have found a few small bugs and suggestions I can put on there for you soon. On Discord, I am "Vulgrim". See you on disc!
