### ISSUE TITLE
[BUG] Quest indicator - wrong quest objective displayed

### ISSUE THREAD

**Issue by BelegCufea** [Voopie/Stripes#13]
**Describe the bug**
The quest indicator appears to be malfunctioning in version 1.29.2 (and 1.29.3 as well), as it displays the first objective of a quest on each quest mob or item quest indicator. At least it seems to me that this is the case.

**To Reproduce**
1. Pick quest with multiple objectives
2. Quest indicator shows wrong value (and type ...)

**Expected behavior**
Up to version 1.29.1 it worked fine.

**Screenshots**

New behavior (1.29.2) - It shows 4 for the number of artifacts I needed to find. It should display 76 (in the sword icon) for missing percentage of completion.
![New behavior (1.29.2)](https://i.imgur.com/0wA7aqA.jpg)

Original behavior (1.29.1)
![Original behavior (1.29.1)](https://i.imgur.com/l2URcy0.jpg)

**Additional context**
Sorry for the plethora of addons cluttering my screen.

**Comment by Voopie** [comment]
Thank you! I think I fixed it :) At least in the same quest everything is fine now

**Comment by BelegCufea** [comment]
Thank you very much.

It seems to be working properly now, just like before.

Have a great day!
