### ISSUE TITLE
[BUG] Health Bar showing/hiding when in NameOnly mode

### ISSUE THREAD

**Issue by BelegCufea** [Voopie/Stripes#15]
When I have Name Only mode enabled (Visibility -> Friendly -> (<<Name only>> mode) -> checked "Enabled", unchecked "Players only"), health bars start to behave funny.

When "Anywhere" is choosen, then when i fight enemy npc,  health bar starts to hide and show regulary.

When "Only in open world", then sometimes healthbar appears for friendly player. This usually happens in a combat (like when fighting rares).

I tried to dig into it (mainly in Handler and Name modules) but no joy.
I tried to "fix" the "Anywhere" choice. The NameOnly_UpdateHealthBar function in Name.lua works correctly and shows healthbar for enempy npc, but then somehow it gets hidden again. It seems Blizz is somehow interfering with the visibility as there is no other place in your code that hides the healthbar :-(
It only started with 10.1 patch.

Meanwhile I was forced to learn how to write modules to Plater to do similar things as your addon (mainly level and health on name only plates and target text), but it sucks big time.

Don't know if you have time and or energy to make a fix. I will try to find some fix myself meanwhile ... (but I am awful at that).

Have a nice day!

**Comment by Voopie** [comment]
I think it's fixed now :)
