### ISSUE TITLE
[BUG] Auras not showing. 

### ISSUE THREAD

**Issue by Timourgv** [Voopie/Stripes#3]
**Describe the bug**
Can't see Aura. 

**To Reproduce**
Use Stripes.

**Expected behavior**
To show auras. 

**Comments**

Those nameplates are super promising. A shame that doesn't matter what I did I couldn't show them. (and yes I tried every option in *Auras)

**Screenshots**
![WoWScrnShot_010522_010630](https://user-images.githubusercontent.com/55139207/148140457-553a0f32-02e9-4551-a565-7bf00c16eb95.jpg)

**Comment by Voopie** [comment]
Hmmm... Very interesting...
Can you send me screenshot from options "Auras / General"?

**Comment by Timourgv** [comment]
![WoWScrnShot_010622_101458](https://user-images.githubusercontent.com/55139207/148359022-2dc020f7-106f-4784-84a1-5dad0a6f8d12.jpg)

Sure thing here. I usually use plater and it works. I tought maybe it would be related to the " name only " variable. I know plater force it off automatically. I tried to enable/disable it to no avail. No error reported by Buggrabber either.

**Comment by Voopie** [comment]
I don't know what to say...
![image](https://user-images.githubusercontent.com/1324849/148381416-f2ff04a7-866b-4e4a-8797-4ae59ed3a45a.png)

I also tried several scenarios with different auras settings and with your settings, but no result
Maybe you have some other addons that touches nameplates at all or nameplates auras? (Like BigDebuffs, NameplateAuras etc.) Or maybe something in ElvUI nameplates options

**Comment by Timourgv** [comment]
Ahhh I got NameplateAuras, I'm using it in cunjunction with Plater. Haven't tried to disable it, elvui nameplates are disabled ofc, BigDebuff is not installed. Will report back after some more testing. It's just odd than it doesn't show any error tbh. (so the issue is probably config related on my side)

**Comment by Voopie** [comment]
Anyway, I will try to make my addon work with NameplateAuras
Oh, I found it, NameplateAuras has a "Hide default Blizzard Auras" (or something like that) setting
