### ISSUE TITLE
[FR] Classcolor support for Target Indicator options

### ISSUE THREAD

**Issue by Pingumania** [Voopie/Stripes#4]
Hey, with my old nameplate addon I used to set my current target color (bar and arrow indicator) to the color of my class I am currently playing. Would love to see this option in Stripes.

A workaround is to create a profile for every class and set the colors manually.

**Comment by Voopie** [comment]
Hi!
Already made it possible and it will be in the next version

**Comment by Voopie** [comment]
A new version with the desired feature is already available 😉
