### ISSUE TITLE
[FR] Stop castbar glow when the cast is interrupted/canceled.

### ISSUE THREAD

**Issue by Pingumania** [Voopie/Stripes#5]
Right now if a mob casts an important spell with the glow effect on, the glow effect stays until the castbar is gone.
This means even if the cast is already interrupted the glow stays and that can be confusing.

**Describe the solution you'd like**
Stop the glow when the cast is interrupted/canceled.

**Comment by Voopie** [comment]
Done! There will be a new version soon
