### ISSUE TITLE
Cast Name Font Size Not Working

### ISSUE THREAD

**Issue by reale411** [Voopie/Stripes#7]
The name of the spell on the cast bar can't be resized using the GUI. No matter what it's set at, it looks to be about size 20 always. Thank you. Maybe add Masque support for all icons including cast bar spell icon.

**Comment by Voopie** [comment]
Hey!
Hmm, everything looks fine from my side

Size 15
![image](https://user-images.githubusercontent.com/1324849/195895240-52822830-c27c-45ff-a241-0288928f9132.png)

Size 7
![image](https://user-images.githubusercontent.com/1324849/195895404-5782bb2f-43ab-4cfd-be8b-ae2fb4e0b84f.png)

About masque for all icons: probably soon after the release of Dragonflight

**Comment by reale411** [comment]
Strange, mine doesn't change. Is it dynamic or do I need to /rl? Thanks for the response :)
![WoWScrnShot_101422_095234](https://user-images.githubusercontent.com/367745/195901337-301bee01-d4db-43d2-af03-db564b487c4c.jpg)
![WoWScrnShot_101422_095250](https://user-images.githubusercontent.com/367745/195901340-43b6ba38-ecee-4e23-bbc9-3b0680b905f8.jpg)
![WoWScrnShot_101422_095306](https://user-images.githubusercontent.com/367745/195901342-4fb349c4-9edb-4995-a9c0-e09923f3732a.jpg)

**Comment by Voopie** [comment]
I have three questions so far:
1) Are you sure you're changing the font size of "Cast name" and not "Cast target name"?
2) I noticed that your "Arial Narrow" font has been replaced by another and through the Fonts folder. Isn't it possible that the new font has only one fixed size? (sounds silly, but still)
3) And please check "Global" section on the left side. Maybe you checked "Use global font size settings"?

**Comment by reale411** [comment]
I adjusted everything above with no luck, so I nuked the addon and saved variables. After a clean reinstall, everything works as supposed to. I must have tweaked something too hard :)

Great addon, fast and focused, appreciate your time and good hunting.
